### ISSUE TITLE
Figure out (or document) a good way to ignore olean files

### ISSUE THREAD

**Issue by gebner** [leanprover/vscode-lean#1]
Right now the explorer sidebar shows both lean and olean files.  If it would only show lean files, then it would be really nice to navigate a project.

Maybe this already works, but I couldn't figure out how.
gitignore doesn't seem to work either: https://github.com/Microsoft/vscode/issues/78

**Comment by leodemoura** [comment]
I managed to hide them by adding `"**/*.olean" : true` to `files.exclude`.
Here is my `settings.json`
```
// Place your settings in this file to overwrite default and user settings.
{

    "files.exclude": {
        "**/.git": true,
        "**/.svn": true,
        "**/.hg": true,
        "**/.DS_Store": true,
        "**/*.olean" : true
    }
}
```

**Comment by jroesch** [comment]
There is an API that exists in the API docs and is in master but doesn't appear to be in VSCode. When this is in the released version we can use it https://github.com/Microsoft/vscode/blob/master/src/vs/vscode.d.ts#L2830.

**Comment by jroesch** [comment]
It appears that it was released but I get an error when I attempt to call it

**Comment by jroesch** [comment]
Never mind I just bumped the version of the editor we support, and now I see the API.
