### ISSUE TITLE
option to supress variables bound to _, in info view

### ISSUE THREAD

**Issue by ratmice** [leanprover/vscode-lean#100]
When binding like: (\lam a _, a), in the info view, it will list a variable e.g. _x : ...
It would perhaps be a nice enhancement if it were possible show/hide these bindings beginning with _ in the info view.

**Comment by bryangingechen** [comment]
I've just made PR #101 which is an attempt in this direction. Please test it out and leave comments there!

**Comment by ratmice** [comment]
With Bryan's PR merged, i think this can be closed.
