### ISSUE TITLE
tab-completion should show all types, and no question marks

### ISSUE THREAD

**Issue by semorrison** [leanprover/vscode-lean#120]
Tab-completion in VS-Code only [shows the type of the selected option, and prepends a `?` to each variable](https://leanprover.zulipchat.com/user_uploads/3121/ykVEWSMsfHNpO985b-l2W2Lm/Screenshot-2019-05-31-16.03.04.png). In emacs it's much nicer: [the type is displayed for every option, and instead of `?` the variables are highlighted](https://leanprover.zulipchat.com/user_uploads/3121/cNzLaymd1BAPcVCzoolsRQaN/Screenshot-from-2019-05-31-16-22-23.png).

**Comment by gebner** [comment]
When I click on the links I only see `You are not authorized to view this file.`  Can you upload the screenshots (?) somewhere else?  (e.g. on github, drag&drop into the issue should work.)

**Comment by semorrison** [comment]
<img width="604" alt="Screenshot-2019-05-31-16 03 04" src="https://user-images.githubusercontent.com/477956/58752344-32e74b80-84a5-11e9-8d81-701e8d1a1535.png">

![Screenshot-from-2019-05-31-16-22-23](https://user-images.githubusercontent.com/477956/58752346-38dd2c80-84a5-11e9-8896-40bed9f976b7.png)

**Comment by bryangingechen** [comment]
It's possible to remove the question marks and to display the types (and tactic params) in the CompletionItem's `label` property, but VS code doesn't support any kind of formatting. [Here's a branch](https://github.com/bryangingechen/vscode-lean/tree/better-completions) where I tried to adjust the completions towards what [the emacs mode does](https://github.com/leanprover/lean-mode/blob/master/company-lean.el)). I'm not sure if I like the result better since it's not as clear to me what will end up inserted.

**Comment by semorrison** [comment]
@bryangingechen, how about we use your branch, but drop the `.replace(/\?([^\s]+)/g, '$1');`?

That way the resulting type will be shown, and I agree if we can't have highlighting then the question marks should just be shown.

**Comment by bryangingechen** [comment]
To be honest, I actually prefer it the other way around, with no question marks and no types displayed by default. However, I'll update my branch as you describe and put the types behind a config option.

**Comment by semorrison** [comment]
Sorry, I didn't see this response before making my other post. I'll admit
to being mystified why you'd prefer not to see the types, but gusta non
disputandum!

**Comment by bryangingechen** [comment]
Hmm, I guess in my brief experience playing around with the new feature it seemed like the completion list was frequently too narrow for the type information to be helpful so I ended up relying on the detail panel on the right like I was used to. I do agree that in general having more info available is better, but currently VS Code just doesn't make this look good enough for this to work for me.

**Comment by semorrison** [comment]
Oh, what is the detail panel on the right? Maybe I'm missing something.

**Comment by bryangingechen** [comment]
I just mean the panel that comes up if you click on the blue circle here:
<img width="430" alt="Screenshot 2019-06-25 18 12 13" src="https://user-images.githubusercontent.com/5209952/60137416-d52ce300-9774-11e9-89dd-6a3a1109628c.png">

It looks like this when it's open:
<img width="657" alt="Screenshot 2019-06-25 18 12 33" src="https://user-images.githubusercontent.com/5209952/60137417-d52ce300-9774-11e9-8242-00f3c8b5d4c9.png">

**Comment by semorrison** [comment]
I see. I'd never noticed that blue circle before.
