### ISSUE TITLE
Info view automatically closes ctrl+p window

### ISSUE THREAD

**Issue by gebner** [leanprover/vscode-lean#132]
This is annoying me to no end.

 1. Focus the info view (e.g. by clicking on it).
 2. Press ctrl+p.
 3. Release ctrl+p.
 4. vscode automatically opens the first file shown by ctrl+p.  (Normally you could type in a file name now.)

This happens with vscode 1.39.1 on linux.

**Comment by bryangingechen** [comment]
I cannot reproduce this with vscode 1.39.2 on macOS.

**Comment by bryangingechen** [comment]
Possibly related? https://github.com/microsoft/vscode/issues/82592

**Comment by gebner** [comment]
> Although if I press or hold cmd+p again after the quick open menu is open (regardless of whether the webview or an ordinary editor is focused) then the quick open item which is selected is opened when I release.

This is interesting.  Here pressing ctrl+p again cycles through the options.

> Possibly related? microsoft/vscode#82592

I don't think so.  F1 opens the quick open menu for me (and not the chrome help).

I'll check whether this happens on a fresh vscode installation as well, and then I'll make a bug report at vscode.

**Comment by gebner** [comment]
This is apparently fixed in vscode now: https://github.com/microsoft/vscode/issues/88284
