### ISSUE TITLE
getting the new leanpkg.toml warning when opening markdown files in other projects

### ISSUE THREAD

**Issue by bryangingechen** [leanprover/vscode-lean#133]
Since 0.14.7, I now see the `leanpkg.toml` warning pop up when I open markdown files in any project in VS Code.

Currently, the extension is launched when either Lean files or markdown files are opened. Is there a way to customize the activation events using the settings? The `lean.input.languages` doesn't seem to affect this. The only solution I see currently is to disable the extension by default and only enable it manually for Lean projects.

**Comment by gebner** [comment]
Ah, thanks for noticing this!  I completely forgot that we now also enable the extension for markdown files.
