### ISSUE TITLE
`\}}` is not substituted correctly

### ISSUE THREAD

**Issue by fpvandoorn** [leanprover/vscode-lean#142]
Writing a `)` or `}` after a backslash ends the input mode.

**Comment by gebner** [comment]
IIRC, the idea was that you could write `{x : \alpha}` and you would immediately get `{x : α}`.  Do you think it's better to stay in input mode?

**Comment by bryangingechen** [comment]
This is also #46.

**Comment by fpvandoorn** [comment]
Oops, closed as duplicate.
