### ISSUE TITLE
Weird files when using vscode's git interface

### ISSUE THREAD

**Issue by gebner** [leanprover/vscode-lean#15]
I just tried to use vscode's built-in git interface to create a commit, and since then I get errors in the files "15", "16", and "17".  AFAICT these are temporary files created by the git interface, and we should ignore them.

We should probably also unload files from the server when they are closed/deleted.

**Comment by jroesch** [comment]
Sounds good, I need to investigate how to do the first part, but there should be events to subscribe to for the second part.

**Comment by semorrison** [comment]
I used to see these errors, but haven't for a long time.

This issue can probably be closed.
