### ISSUE TITLE
improve introspection for variables in lemmas

### ISSUE THREAD

**Issue by garfieldnate** [leanprover/vscode-lean#168]
I'm working on the very first Lean tutorial (`00_first_proofs.lean`).

An example of my issue is lemma `inf_lt`. The given proof uses the `.2` syntax for accessing part of the `x is_an_inf_of A` assumption. I found the tutorial text difficult to follow because I did not remember which part of the `is_an_inf_of` assumption was which. As you can see below, mousing over the `.2` syntax gives information on the `exact` tactic instead of explaining the second part of the assumption as expected:

![image](https://user-images.githubusercontent.com/778453/84528899-d4bc8d80-ace0-11ea-9868-da2f46f350bc.png)

Right-clicking `.2` and choosing `Go To Definition` also takes me to the definition of the `exact` tactic. I also tried mousing over the `hx` in the goals area, but no information is given there. Inspecting `hx` doesn't do what I would expect, either; the expected behavior is to show or jump to the declared assumption, but instead it brings the goal window into focus.

This makes it quite a bit more difficult to work through the tutorial. In the case of the `.2`, to find the definition the user must locate the declaration of hx (not difficult but still an extra step), then follow the trail via `is_an_inf_of` -> `is_a_max_of`.

**Comment by bryangingechen** [comment]
As I said (perhaps too obliquely) on Zulip, the issues with `exact` are Lean issues, so the right place to open an issue is [at the community Lean repo](https://github.com/leanprover-community/lean/issues).

**Comment by garfieldnate** [comment]
Ah, my bad. I'm not really sure how to translate this issue into a core lean issue. Can you advise me on that? Or can I just paste this whole thing, with the VS code image and everything, and the maintainers will understand the issue?

**Comment by bryangingechen** [comment]
No big deal, you can just copy and paste this text over there. And yes, the community Lean maintainers are very much in touch with the vscode extension...

**Comment by garfieldnate** [comment]
All migrated.
