### ISSUE TITLE
Error messages do not update in info view

### ISSUE THREAD

**Issue by gebner** [leanprover/vscode-lean#173]
1. Open the following file in vscode:
```
example : false := trivial
```
2. Close the info view.
3. Open the info view.
4. The error message is not shown.

cc @EdAyers

**Comment by gebner** [comment]
Hmm, I still get the issue:
![missing_errors](https://user-images.githubusercontent.com/313929/84805863-2fb5f380-b005-11ea-910b-a4f09f5d7628.png)

**Comment by EdAyers** [comment]
What info should be there?

**Comment by EdAyers** [comment]
The problem seems to be that it's not picking up the messages. Can you confirm that the goal state is fine for you?

**Comment by EdAyers** [comment]
Is there a way to request tht Lean fires another 'all_messages' response?

**Comment by gebner** [comment]
> Can you confirm that the goal state is fine for you?

Yes, goal state and "all messages" are fine.

> Is there a way to request tht Lean fires another 'all_messages' response?

No, you need to store this yourself.

**Comment by EdAyers** [comment]
Ok, the problem is that you can't store it if the entire webview has been reloaded. I can fix by making the extension code forward the initial value for messages to the webview?

**Comment by EdAyers** [comment]
Also does it still make sense to have a separate 'lean messages' and 'lean goal' mode, since the only difference is whether 'all messages' collapsible is present.

**Comment by EdAyers** [comment]
For me "all messages" is also not populated if I reload the infoview

**Comment by gebner** [comment]
> Also does it still make sense to have a separate 'lean messages' and 'lean goal' mode

I don't think so.  But I've also never used the "lean messages" mode.  Maybe ask on zulip whether people know this exists.
