### ISSUE TITLE
Support looking for leanpkg.toml and leanpkg.path in any subdirectory of the workspace

### ISSUE THREAD

**Issue by utensil** [leanprover/vscode-lean#192]
If one opens the lean file `examples/src/sandwich.lean` in https://github.com/leanprover-community/format_lean , the VSCode extension would complain that it's not supported. Also, it would fail to find the mathlib and import files from it normally.

By reading https://github.com/leanprover/vscode-lean/blob/master/src/leanpkg.ts , it seems adding the recursive search for this file is not entirely impossible(and it seems that the changes can be limited in this file), but I don't know if there're further implications so that it's better to keep it simple and not to implement this feature. If this feature is desired and the changes can indeed be limited in this file, then I could file a PR as how I imagined it.

x-ref: https://github.com/leanprover-community/mathlib-tools/issues/59

**Comment by gebner** [comment]
The `leanpkg` part is a red herring.  The stuff that actually breaks is that we need to start the lean server in the directory with the `leanpkg.path` file, and (this is where it requires a lot of refactoring) if there are multiple `leanpkg.path` files, we'd need to start multiple lean servers.

This would also be interesting for #63.

**Comment by utensil** [comment]
I see. It's indeed more complicated than I thought. I'll just open the directory directly for now, this is not much trouble for an end-user.

**Comment by PatrickMassot** [comment]
There is no need to change anything to the VSCode extension be able to open the example from `format_lean`. After cloning the `format_lean` repository, you can:
```
cd examples
git init
leanproject get-mathlib-cache
code .
```

**Comment by utensil** [comment]
Thank you for the tip and it did the trick. Closing.
