### ISSUE TITLE
Number of "Lean: Proof Context" output channels increases steadily

### ISSUE THREAD

**Issue by gebner** [leanprover/vscode-lean#2]
Every time the user uses show-goal, we generate a new output channel.  Apparently the old ones don't get removed or overwritten.  You can see the effect if you click on "Lean: Proof Context" in the output subwindow.

**Comment by jroesch** [comment]
How do we want to manage them, one per file? one globally? per file seems best to me. I often get annoyed with proof general requiring me to destroy the proof state of one file to look at another.

**Comment by gebner** [comment]
I think a single global buffer should be enough.  As you said, getting the current goal is almost for free in lean.

**Comment by jroesch** [comment]
We can always revisit it in the future then, closing.
