### ISSUE TITLE
CSS priority

### ISSUE THREAD

**Issue by PatrickMassot** [leanprover/vscode-lean#205]
I just tried to use the VSCode extension setting that allow to give extra CSS classes. It works great except that it doesn't take precedence over the default CSS. I think user preferences should have priority.

For instance, you can try putting: `.goal-goals {     color: red; ! important }` which won't work without the `! important`.

**Comment by gebner** [comment]
I'm not a CSS guru.  We literally paste the user CSS into the info view stylesheet.

Is there an obvious way to embed it so that it has higher priority?  We could also use a CSS parsing library to add `!important` to every property.

**Comment by PatrickMassot** [comment]
It's not about being a CSS guru, it's all about this react thing. The user CSS is included [here](https://github.com/leanprover/vscode-lean/blob/master/src/infoview.ts#L359) but then https://github.com/leanprover/vscode-lean/blob/master/src/infoview.ts#L363 comes later, calling https://github.com/leanprover/vscode-lean/blob/master/infoview/index.tsx#L7 probably. So maybe the config reading which is currently at https://github.com/leanprover/vscode-lean/blob/master/src/infoview.ts#L149 should be move in https://github.com/leanprover/vscode-lean/blob/master/src/infoview.ts. Really I have no idea what I'm talking about.

**Comment by gebner** [comment]
Ah, so CSS rules that come later have precedence over earlier ones (if they have the same selector).  I have no idea how to include the `index.css` first.  This seems to be some webpack magic.  @EdAyers ?
