### ISSUE TITLE
Pretty-print the expression in widget mode

### ISSUE THREAD

**Issue by DanielFabian** [leanprover/vscode-lean#218]
When you have longer expressions, the text and widget modes render very differently. It would be very nice if we could also pretty-print in the widget mode. Here's an example:

```lean
example : ∀ n : ℕ, to_string n ≠ "hello" :=
begin
    intro n, dsimp [to_string, has_to_string.to_string, repr, has_repr.repr, nat.repr, nat.to_digits],
    delta nat.to_digits,
    -- put your cursor here
end
```

![image](https://user-images.githubusercontent.com/1929340/89710736-7e389c00-d97d-11ea-9f40-cc3eff7908bf.png)

The top state is rendered using widget mode, the bottom one is just text, but they both refer to the same proof state.

**Comment by gebner** [comment]
cc @EdAyers in case you have any ideas

**Comment by EdAyers** [comment]
Yes at the moment the interactive expression renderer throws away the line and nesting information (you can see this in `interactive_expr.lean`, the tagged_format type is first passed to a simpler inductive datatype). This was just for expediency in getting it working, but iirc all the formatting information is available in principle without needing to rewrite any C++.

**Comment by EdAyers** [comment]
So this issue should be moved to the lean repo or mathlib, it's not a vscode problem

**Comment by DanielFabian** [comment]
are you suggesting that you are already using the information but simply get a simplified version of it, or would the vscode extension still need some adjustment. If the former, we can close it, if the latter, then I an look into doing the lean changes and if I fail, at least I'll open an issue and reference this one.

**Comment by EdAyers** [comment]
This is the code which removes the formatting information that would need to change: https://github.com/leanprover-community/mathlib/blob/77f3fa47786a767132593c94fae83b374d6462e9/src/tactic/interactive_expr.lean#L65

**Comment by EdAyers** [comment]
The vscode extension does not need to be adjusted

**Comment by DanielFabian** [comment]
Closing as per discussion. I'll look if I can fix it in mathlib, if not, I'll open an issue. thanks!
