### ISSUE TITLE
Add configuration option for setting Lean flags

### ISSUE THREAD

**Issue by jroesch** [leanprover/vscode-lean#22]

**Comment by johoelzl** [comment]
Is there a specific application for it? Do you want to set Lean options, or command line flags?

It looks like https://github.com/leanprover/vscode-lean/commit/8906439758cd795da948efbb2d8aa568e4f70ef9 implements most applications of additional command line flags.

**Comment by jroesch** [comment]
I think we should add specific settings for commonly used flags, as well as an`otherFlags` option which always allows users to pass them in case we don't have support.
