### ISSUE TITLE
markdown can make comment syntax highlighting extend past the end of the comment

### ISSUE THREAD

**Issue by rwbarton** [leanprover/vscode-lean#229]
In
```lean
/-
~~~
-/
example : true :=
trivial
```
all the lines are treated as comments.

In
```lean
--- comment
  all

  these
  lines
  are

gray
not gray
```
all lines up to and including the first non-indented line are treated as part of the comment. The same thing occurs with the syntax
```lean
-- * foo

example : true :=
trivial
```

Because GitHub uses the vscode-lean grammar for Lean syntax highlighting, these problems are also visible here in the text of this issue.

**Comment by gebner** [comment]
The first one still gives unexpected results, but that's because it's not well-nested markdown (`~~~` means `` ```markdown ``).

I don't think you can easily make this kind of nesting work in textmate grammars, since the markdown grammar is applied greedily.  Every production in the markdown grammar would hence need to check for `-/`.

**Comment by rwbarton** [comment]
Would it be possible/sensible to limit markdown processing in comments to docstring and module docstring comments (things that end up in the documentation), and treat plain old comments as just containing freeform text? For example, I might comment out a big chunk of my Lean file and it doesn't make sense to try to process that as markdown.

**Comment by gebner** [comment]
Highlighting markdown in normal comments was explicitly requested by @PatrickMassot: https://leanprover.zulipchat.com/#narrow/stream/113488-general/topic/comments.20highlighting/near/203446418

We could disable the highlighting for `~~~` if that helps, I don't think anybody uses that markup.

**Comment by rwbarton** [comment]
OK, if the current behavior is intentional, I certainly won't argue with actual users of vscode!
I agree the `~~~` thing is particularly obscure--I knew it had to be responsible in the situation where I originally saw this because there was nothing else suspicious in the comment, but out of context I would have guessed `~~~` makes an hrule or something.
