### ISSUE TITLE
Lean sometimes tries processing git diffs.

### ISSUE THREAD

**Issue by semorrison** [leanprover/vscode-lean#24]
If I'm working on a project managed in git, sometimes when I use the git view in Visual Studio Code to look at diffs of files, it seems that the Lean extension is trying to process the diffs, which causes huge lists of spurious errors.

**Comment by gebner** [comment]
This is the same underlying issue as #15.  We should ignore the temporary files opened by the git interface.

**Comment by semorrison** [comment]
Oops, thanks, I missed that one.
