### ISSUE TITLE
Is lean 4 supported by the extension?

### ISSUE THREAD

**Issue by Kariiem** [leanprover/vscode-lean#252]

**Comment by bryangingechen** [comment]
No. The Lean 4 VS Code extension is [here](https://github.com/mhuisi/vscode-lean4).

**Comment by MatthijsBlom** [comment]
Are there ambitions or plans to provide support for Lean 4 in the future, perhaps by merging with mhuisi/vscode-lean4?

Failing to think of any reasons why it wouldn't be, I imagine the ideal situation would be, for the ordinary user, to have only one extension that can deal with all Lean versions. I wouldn't know anything about why this would perhaps be difficult to achieve though.

**Comment by bryangingechen** [comment]
There was a discussion in [this Zulip thread](https://leanprover.zulipchat.com/#narrow/stream/270676-lean4/topic/Home.20of.20vscode-lean4/near/222167892) but I believe the outcome was that the extensions will be separate for now.
