### ISSUE TITLE
Latest update of vscode-lean automatically converts latex expression to symbol in markdown files

### ISSUE THREAD

**Issue by kingvagabond** [leanprover/vscode-lean#257]
I have almost 100 VS code extension installed, and after update extensions I found I cannot type latex symbols in markdown files. They are automatically converted to some symbols that I don't want to. And it is not controlled to disable this feature as to my knowledge. So I disabled all extensions to recover it to normal behavior and enable extension one by one to check who made this trouble.

Unfortunately, it is vscode-lean. Please rethink about the latest change to this extension and fix this issue. This is a terrible behavior.

**Comment by bryangingechen** [comment]
Could you test out #256 and see if it fixes your issue?

**Comment by bryangingechen** [comment]
The artifact linked at the bottom of [this page](https://github.com/leanprover/vscode-lean/actions/runs/523784949) is a ZIP file which contains [a `.vsix` file that you can try out](https://code.visualstudio.com/docs/editor/extension-gallery#_install-from-a-vsix).

**Comment by kingvagabond** [comment]
> The artifact linked at the bottom of [this page](https://github.com/leanprover/vscode-lean/actions/runs/523784949) is a ZIP file which contains [a `.vsix` file that you can try out](https://code.visualstudio.com/docs/editor/extension-gallery#_install-from-a-vsix).

Tried to open the zip or vsix file but vs code complains it's binary and does not install the extension.

**Comment by gebner** [comment]
I've just published a new version with the fix from #256.  You should be able to update it from the extension tab.

**Comment by kingvagabond** [comment]
> The artifact linked at the bottom of [this page](https://github.com/leanprover/vscode-lean/actions/runs/523784949) is a ZIP file which contains [a `.vsix` file that you can try out](https://code.visualstudio.com/docs/editor/extension-gallery#_install-from-a-vsix).

ran the command but did not get it installed

C:\Users\Administrator\Desktop>
code --install-extension lean-0.16.22.vsix

C:\Users\Administrator\Desktop>
[main 2021-02-02T18:18:40.840Z] update#setState idle
(node:38556) Electron: Loading non-context-aware native module in renderer: '\\?\C:\Program Files\Microsoft VS Code\resources\app\node_modules.asar.unpacked\vscode-sqlite3\build\Release\sqlite.node'. This is deprecated, see https://github.com/electron/electron/issues/18397.
(node:38556) Electron: Loading non-context-aware native module in renderer: '\\?\C:\Program Files\Microsoft VS Code\resources\app\node_modules.asar.unpacked\node-pty\build\Release\pty.node'. This is deprecated, see https://github.com/electron/electron/issues/18397.
(node:38556) Electron: Loading non-context-aware native module in renderer: '\\?\C:\Program Files\Microsoft VS Code\resources\app\node_modules.asar.unpacked\windows-process-tree\build\Release\windows_process_tree.node'. This is deprecated, see https://github.com/electron/electron/issues/18397.
(node:38556) Electron: Loading non-context-aware native module in renderer: '\\?\C:\Program Files\Microsoft VS Code\resources\app\node_modules.asar.unpacked\spdlog\build\Release\spdlog.node'. This is deprecated, see https://github.com/electron/electron/issues/18397.
(node:13180) Electron: Loading non-context-aware native module in renderer: '\\?\C:\Program Files\Microsoft VS Code\resources\app\node_modules.asar.unpacked\spdlog\build\Release\spdlog.node'. This is deprecated, see https://github.com/electron/electron/issues/18397.
[main 2021-02-02T18:19:10.842Z] update#setState checking for updates
[main 2021-02-02T18:19:10.895Z] update#setState idle

**Comment by kingvagabond** [comment]
> I've just published a new version with the fix from #256. You should be able to update it from the extension tab.

Yes, confirmed this is fixed after update in extension tab.
