### ISSUE TITLE
Quoted Text Coloring

### ISSUE THREAD

**Issue by BoltonBailey** [leanprover/vscode-lean#260]
AN example of this issue can be seen [here](https://youtu.be/Y7zjInL82-Q?t=700). When the ` is placed before the `nat`, `nat` is highlighted in lavender. But when the ` is placed before the `int`, not only does the `int` turn lavender, but the `]` after the `int` turns lavender as well.

**Comment by eric-wieser** [comment]
I think this is fixed by #273. At any rate, I can't reproduce that as @robertylewis is using a custom color scheme.
