### ISSUE TITLE
Extension seems to ignore lean.executablePath option

### ISSUE THREAD

**Issue by vitaliyparinov** [leanprover/vscode-lean#28]
A regression since the previous version: the extension is unable to start lean now. Right after VS Code start it fails with a "The lean.executablePath may be incorrect, ensure the variable is a valid Lean executable" warning and an "Unable to start the Lean server process: Error: Command failed: lean --version" error, despite the fact that the value of the "lean.executablePath" option hasn't been changed and still points to the correct lean executable. The platform is Windows and I don't have lean in $PATH.

**Comment by jroesch** [comment]
I believe this is fixed as of `0.6.5`, if it is not the case let me know. 

I am still trying to best understand how to test the editor in a cross platform way, especially since many of the features rely on interacting with a live server process, and user events.

**Comment by vitaliyparinov** [comment]
Yeah, it works for me now, thanks!

Don't really have any advice on testing though.
