### ISSUE TITLE
"end" colorized incorrectly

### ISSUE THREAD

**Issue by BoltonBailey** [leanprover/vscode-lean#282]
I noticed this after enabling the "Editor › Bracket Pair Colorization" option: The three letter sequence "end" is highlighted red, even when it occurs in the middle of a word.

<img width="821" alt="Screen Shot 2021-11-03 at 7 03 38 PM" src="https://user-images.githubusercontent.com/8030599/140235936-95246abf-d475-45b9-bf98-8472e21eeef5.png">

The "end" in the match statement is red correctly, but the "app(end)" red looks bad.

**Comment by bryangingechen** [comment]
Yeah, we should probably remove the `begin` `end` pairs from the list of brackets.

cc: @eric-wieser who added this (I think)

**Comment by BoltonBailey** [comment]
> Yeah, we should probably remove the `begin` `end` pairs from the list of brackets.

It would be nice, though, if typing begin-TAB in the editor automatically generated a begin-end pair and indented it automatically. I personally have written a snippet to do this for me. Perhaps adding that feature to the lean VSCode extension is a separate issue though.

**Comment by gebner** [comment]
Fixed by 7c891a6519b0aeaaeeb5384f22bd98b8abda0aa9
