### ISSUE TITLE
Consider using `message.end_pos` in diagnostics

### ISSUE THREAD

**Issue by eric-wieser** [leanprover/vscode-lean#300]
Putting this here so I don't forget

https://github.com/leanprover/vscode-lean/blob/5c24ccd41c2cb992871a39c19f5ba132db7b148c/src/diagnostics.ts#L60-L68

The server now sends end positions:

https://github.com/leanprover-community/lean/blob/bfce34363b0efe86e93e3fe75de76ab3740c772d/src/shell/server.cpp#L196-L197

It would be worth trying to use them.

**Comment by gebner** [comment]
> The server now sends end positions:

You're linking to the wrong code.  The link goes to the current tasks message, which is used for the orange progress bars.

Lean 3 only sends end positions with `#print` (iirc).  I firmly believed that we use the end position for that single command, but apparently not.

**Comment by eric-wieser** [comment]
I think I ended up implementing this in my other PR anyway; indeed, it seems to not actually send `end_pos` most of the time.
