### ISSUE TITLE
"Try this:" fails on messages with quotation marks

### ISSUE THREAD

**Issue by robertylewis** [leanprover/vscode-lean#308]
The `Try this:` feature seems to fail when the message contains the `"` symbol, balanced or otherwise. 

```lean
meta def oops : tactic unit :=
tactic.trace "Try this: \"hi " 

example : true := 
by oops
```

**Comment by eric-wieser** [comment]
The bug is here:

https://github.com/leanprover/vscode-lean/blob/a41c8f55e28270215d2f5245b9a09db93e4db6a0/infoview/messages.tsx#L31
