### ISSUE TITLE
request: capturing the cause of the Lean server stopping

### ISSUE THREAD

**Issue by semorrison** [leanprover/vscode-lean#31]
I'm seeing very frequent errors which are causing the Lean server to stop (this afternoon I've had a dozen, at least). I have made a few attempts to reproduce them, without success. Running Lean at the command line is fine.

Is there some way that the VS Code extension could capture some error output from the Lean server, so that the underlying bug can be reported?

**Comment by jroesch** [comment]
I'm a little frustrated that VScode doesn't have a better builtin solution to this, this is something Atom seems to do much better. 

I will investigate this, and try to come up with a solution next week. I am super busy this week, it is the end of the quarter at UW and I have my final PhD course to finish, a paper to write, PhD student visit days (which is run by students) and miscellaneous things to wrap up before starting at MSR. I'll try to address this next weekend or on 3/20 Pacific time.

**Comment by jroesch** [comment]
This should now be fixed in master, when the server exits it will display an option to view the "Show error log", which will record standard error, and server errors to that output window.
