### ISSUE TITLE
#eval output only highlights the #

### ISSUE THREAD

**Issue by digama0** [leanprover/vscode-lean#34]
With the new names `#eval` etc (https://github.com/leanprover/lean/issues/1432), the output green squiggle in VS code is on the `#` instead of the whole word, which makes it harder to locate and view. My recommended solution is to make these all recognized as keywords.

**Comment by jroesch** [comment]
I've tried to fix this issue multiple times, but I am not sure how to get VSCode to extend the squiggles, even manually hardwiring and increased range, and changing the word pattern appear to have no effect. Thoughts @Kha @gebner ?

**Comment by gebner** [comment]
Works for me, I've just added support for `#print` as well.

**Comment by gebner** [comment]
Oh, different problem.  I was referring to the syntax highlighting.  This is the error range.

**Comment by gebner** [comment]
Fixed in https://github.com/leanprover/vscode-lean/commit/48a930739a2c6403376b93969511eabfb736a143
