### ISSUE TITLE
request: Show parsing status for imports, even when they are not part of the region of interest.

### ISSUE THREAD

**Issue by semorrison** [leanprover/vscode-lean#40]
I have some files that take a while to parse, and it would be very helpful to me if, when I have another file open that depends on such a file, the Problems panel showed the parsing status of the imported file, even if it would not otherwise be part of the the region of interest. I don't mind not seeing error messages (as these will eventually turn into "imported file ... uses sorry").

**Comment by semorrison** [comment]
(Sorry for the flood of issues. Obviously this one makes no sense unless #39 is resolved anyway.)

**Comment by jroesch** [comment]
cc @gebner

**Comment by johoelzl** [comment]
One option would be to use the experimental **proposed** tree-view API. Where proposed means it still may change or go away in future versions of VS Code. But this could provide a side bar view on the status of all imported theories.

https://github.com/Microsoft/vscode-extension-samples/tree/master/tree-view-sample
