### ISSUE TITLE
Cannot type ⦄ using unicode input

### ISSUE THREAD

**Issue by gebner** [leanprover/vscode-lean#46]
The abbreviation is `\}}` but we already abort after the first curly brace.

**Comment by bryangingechen** [comment]
I noticed this too. I think the current workaround is to use `\{{}}`.

**Comment by gebner** [comment]
Another workaround is to input `\x`, then move the cursor one character left and change it to `\{{x`, and finally remove the `x`...

**Comment by fpvandoorn** [comment]
After fixing this, typing `{x : \alpha}` will not substitute yet immediately into `{x : α}`. 
I think that is a little confusing, but I still think that would be better than making it hard to type `⦄`.

**Comment by gebner** [comment]
Okay, let's try this out in the wild!  I'll blame you if there are any problems. :smile:
