### ISSUE TITLE
lean doesn't work for me in vscode on windows

### ISSUE THREAD

**Issue by fpvandoorn** [leanprover/vscode-lean#65]
I installed Lean on Windows (Windows 10 Home) using `msys2` following the installation instructions, which is happy about my installation:
```
$ lean --version
Lean (version 3.2.1, commit d82df26ff0cf, Release)
```
However, when opening a lean file in vscode (with the extension), Lean is not found, and I get the errors `Lean: leanpkg.path does not exist` and `Lean: Error: Command failed: lean --version`.

`lean.exe` is located in `D:\projects\lean\bin` which is part of my Windows system path. However, even if I change `"lean.executablePath"` to something else (I tried all of the following, which one should I use?):
```
"lean.executablePath": "lean.exe"
"lean.executablePath": "D:\projects\lean\bin\lean.exe"
"lean.executablePath": "D:\\projects\\lean\\bin\\lean.exe"
"lean.executablePath": "/d/projects/lean/bin/lean"
```
However, I'm not sure if it has anything to do with the path at all: if I open Windows PowerShell (which is also the terminal I get in the `Terminal` tab in vscode), and run `lean --version` I get no output (but also no error, which I would get if I write something it cannot find)
```
PS D:\projects\lean\bin> .\lean.exe --version
PS D:\projects\lean\bin> .\lean --version
```
Alternatively, if I run `lean --version` in `cmd` I get errors that some `dll` files are not found (namely `libgmp-10.dll libstdc++-6.dll libwinpthread-1.dll libgcc_s_seh-1.dll`). Presumably the necessary packages are installed only for msys2 and not for the rest of windows?

How should I proceed? Can I make `msys2` the terminal of `vscode` (and how?) and does that affect how `lean` is run in vscode?

**Comment by fpvandoorn** [comment]
I asked Rob and he could solve this error for me by adding `path/to/msys/mingw64/bin` to my Windows system path. Maybe this can be documented somewhere?

**Comment by gebner** [comment]
This workaround is now mentioned in the readme.  We actually try to set the PATH from within the vscode extension, but for some reason this does not work at the moment, see #43.
