### ISSUE TITLE
Spurious "command expected" errors

### ISSUE THREAD

**Issue by kevinsullivan** [leanprover/vscode-lean#76]
I've seen this quite a few times now. I'm editing lean code in the VS Code extension. An error is flagged with a red underline. The tool type indicates "command expected." But the code is correct. For students, this is really confusing. Even for me it's confusing. The solution is usually to right click, bring up the VS Code command pallet, search for the lean commands, and "restart" lean. The error goes away. As far as I recall, these errors tend to crop up when writing proofs of theorems, but I could be wrong about that.

**Comment by gunkWhipper** [comment]
Having this same issue. Anything written in vscode gives 'command expected'. Running the same code in the online browsers works fine.
