### ISSUE TITLE
ctrl+shift+enter opens current file on the side

### ISSUE THREAD

**Issue by gebner** [leanprover/vscode-lean#77]

**Comment by johoelzl** [comment]
Hm, should we change it to `Ctrl-K V`? This is what Markdown Preview uses.

**Comment by gebner** [comment]
I'm not against changing it, but it requires everyone to relearn the keybinding.  Not sure if it's worth just for consistency with the markdown preview.

**Comment by johoelzl** [comment]
Well, If the change to webview panel is enough, that's fine too.
As far as I understand there are no other big changes associated with this?

**Comment by gebner** [comment]
No, it should work like before.  Just in case the issue was not clear: this was not a problem with the keybinding, executing the info view command manually also resulted in duplicating the current editor in the new column.

**Comment by johoelzl** [comment]
Ah! Thanks for clarification.
