### ISSUE TITLE
Spurious errors in comment blocks

### ISSUE THREAD

**Issue by kevinsullivan** [leanprover/vscode-lean#78]
I'm seeing quite a few spurious errors inside comment blocks. These are very confusing to students, if nothing else. See the screen shot here. The second underline, under "What", expands into multiple errors, including unable to synthesize placeholder, etc. A right click "Restart Lean" clears these errors. 
<img width="1280" alt="screen shot 2018-07-25 at 12 13 33" src="https://user-images.githubusercontent.com/2771957/43213513-c3c80dec-9004-11e8-82ae-aa12345eb06e.png">

**Comment by gebner** [comment]
1. Can you show the error messages?
2. Please try the following: click on `(checking visible lines and above)` in the status bar, and then select `visible files`.  Does that fix the problem?

**Comment by kevinsullivan** [comment]
I tried to screen grab the error message on my mac but, wouldn't you know
it, when I push the shift key to do a screen grab, the error message goes
away. I'll try to see if there's another way to do it other than by just
typing it in by hand.

**Comment by gebner** [comment]
This should be fixed with the new defaults.  Please reopen if you still see the problem.
