### ISSUE TITLE
comments after imports not being colored properly

### ISSUE THREAD

**Issue by bryangingechen** [leanprover/vscode-lean#82]
I'm back again with some more examples:
```lean
import data.set -- comment
import /- another comment -/ data.list.basic /- yet another comment -/
```

**Comment by gebner** [comment]
You're faster at reporting bugs than I'm at pressing the release button. :smile:

The fix was already in the master branch, but just not released.  Version 0.11.17 was released a few seconds ago which fixes this issue.
