### ISSUE TITLE
Auto-closing for unicode pairs such as ⟨ ⟩ etc.

### ISSUE THREAD

**Issue by luxbock** [leanprover/vscode-lean#89]
I see that the pair ⟨ ⟩ is [defined](language-configuration.json#L54) as an `autoClosingPair`, and if I insert `⟨` via copy/paste I get the matching closing pair as expected. However this does not work when using the usual insertion method via the input leader key i.e. `\<`.

Given how often one types this pair in particular, it would be awesome if instead of `\<foo\>`, it'd be enough to type `\<foo` and you'd end up with the same result.

**Comment by gebner** [comment]
Should be fixed by #96
