### ISSUE TITLE
autocomplete after `import ` 

### ISSUE THREAD

**Issue by diakopter** [leanprover/vscode-lean#9]
would really help for someone exploring what's available

**Comment by Kha** [comment]
Now supported via https://github.com/leanprover/lean/commit/7040844f9abb5b7ac2837bb27636e0d1d50c3470 / https://github.com/leanprover/vscode-lean/commit/f60fcce05579d54aac571f6bb702151cb5448dd3.

**Comment by jroesch** [comment]
This should now be working.
