### ISSUE TITLE
"Install lean using elan" in extra places

### ISSUE THREAD

**Issue by khoek** [leanprover/vscode-lean#95]
There is a bug where, when the extension generates any little "popup" box in the bottom corner of the screen (say the warning for the case when leanpkg.path has been updated and you are prompted as to whether you want to reload), "Install lean using elan" is presented as an option.

**Comment by khoek** [comment]
(As opposed to just when lean can't be found by the extension.)

Another case is when lean crashes due to the delivery of a signal, and the extension prompts you to "Restart lean".

**Comment by bryangingechen** [comment]
Thanks for the report; this has been fixed in 8fa6705.
